---
title: "automl"
output: html_document
---

```{r}
library(h2o)
# Start the H2O cluster (locally)
h2o.init()
```
# Carga y procesamiento de datos

```{r}
# Import a sample binary outcome train/test set into H2O
train <- h2o.importFile("https://s3.amazonaws.com/h2o-public-test-data/smalldata/higgs/higgs_train_10k.csv")
test <- h2o.importFile("https://s3.amazonaws.com/h2o-public-test-data/smalldata/higgs/higgs_test_5k.csv")
```

# Ejecución de AutoML

```{r}
# Identify predictors and response
y <- "response"
x <- setdiff(names(train), y)
```

```{r}
# For binary classification, response should be a factor
train[, y] <- as.factor(train[, y])
test[, y] <- as.factor(test[, y])
```

```{r}
summary(train)
```



```{r}
# Run AutoML for 20 base models
aml <- h2o.automl(x = x, y = y,
  training_frame = train,
  max_models = 5,
  seed = 1301
)
```

```{r}
aml
```

```{r}
# View the AutoML Leaderboard
lb <- aml@leaderboard
print(lb, n = nrow(lb)) # Print all rows instead of default (6 rows)
```

```{r}
# Get the best model
best_model <- aml@leader
best_model
```

```{r}
h2o.performance(best_model, newdata = test)
```

```{r}
h2o.confusionMatrix(best_model, newdata = test)
```


