---
title: "iris"
output: html_document
---

```{r}
library(h2o)
h2o.init()
```

# Carga de datos en el cluster H2O

```{r}
data(iris)
h2o_iris <- as.h2o(iris)
```
# Exploración inicial de los datos

```{r}
h2o.summary(h2o_iris)
```

```{r}
h2o.hist(h2o_iris$Sepal.Length, breaks=20)
```

```{r}
# Muestreo de datos para un pairplot
#h2o_sample <- h2o.sample(h2o_iris, 50, seed = 1301)
#iris_smp <- as.data.frame(h2o_sample)

#pairs(iris_smp[,c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width")], col = iris_smp$Species)
pairs(iris[,c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width")], col = iris$Species)
```


Troceado del dataset

```{r}
splits <- h2o.splitFrame(h2o_iris, ratios = 0.8, seed = 1301)
train <- splits[[1]]
test <- splits[[2]]
```

Definición de variables predictoras y objetivo

```{r}
X <- c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width")
y <- "Species"
```

# Entrenamiento del modelo de clasificación

```{r}
model <- h2o.gbm(x = X, y = y, training_frame = train, 
                 ntrees = 20, max_depth = 4,
                 seed = 1301)
```

```{r}
model
```
# Evaluación del modelo

```{r}
pred <- h2o.predict(model, test)
```
```{r}
cm <- h2o.confusionMatrix(model, test)
cm
```

```{r}
cmm <- as.matrix(cm[1:3,1:3])
accuracy <- sum(diag(cmm)) / sum(cmm)
accuracy
```


```{r}
model2 <- h2o.randomForest(x = X, y = y, training_frame = train, 
                          seed = 1301)
```

```{r}
model2
```

```{r}
pred2 <- h2o.predict(model2, test)
```


```{r}
cm2 <- h2o.confusionMatrix(model2, test)
cm2
```
```{r}
cmm2 <- as.matrix(cm2[1:3,1:3])
accuracy2 <- sum(diag(cmm2)) / sum(cmm2)
accuracy2
```

# Explotación del modelo

```{r}
new_data <- data.frame(Sepal.Length = c(5.1, 6.7),
                       Sepal.Width = c(3.5, 3.1),
                       Petal.Length = c(1.4, 4.7),
                       Petal.Width = c(0.2, 1.5))
h2o_new_data <- as.h2o(new_data)

h2o.predict(model2, h2o_new_data)
```
```{r}
h2o.predict(model, h2o_new_data)
```

